### ISSUE TITLE
Cloning fails

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/ClinicalTrialsWGETL#1]
see error
(either original or my fork - crashes in official client

![image](https://user-images.githubusercontent.com/7526119/90824195-023b3e00-e305-11ea-8afc-dd52510b625b.png)

**Comment by FilippSolovev** [comment]
Hm, interesting 🤔
I cloned the repository without any problems, but I used terminal command.
Can you try to do the same? I mean `git clone`  command?

**Comment by EmV25** [comment]
I had the same issue. Are you using Windows as well? I fixed it by restoring all staged files except "docs/md_files/Icon", since this one apparently has a conflicting file path.

**Comment by vojtechhuser** [comment]
can the admin delete file 

![image](https://user-images.githubusercontent.com/7526119/93529175-79b2bc00-f909-11ea-9cde-a31970b65e00.png)

or somehow reset that folder...

**Comment by vojtechhuser** [comment]
the problem is still there.

**Comment by FilippSolovev** [comment]
Could you try again? I deleted that file.

**Comment by vojtechhuser** [comment]
it works now
