### ISSUE TITLE
MOP to SDTM transform mapping and ETL job

### ISSUE THREAD

**Issue by vagarwal77** [OHDSI/ClinicalTrialsWGETL#3]
Any idea to point OMOP to SDTM transform mapping and ETL job ?

**Comment by FilippSolovev** [comment]
Thanks for your interest. Right now, our efforts are concentrated in the opposite direction - moving data from SDTM to OMOP. So converting of OMOP to SDTM is a task for the far future.

**Comment by vagarwal77** [comment]
@FilippSolovev  I am also interested to transform SDTM to OMOP. Please suggest where i can get the direction for the same?

**Comment by FilippSolovev** [comment]
@vagarwal77 watch this repository, here we are converting synthetic PHUSE data, which is in SDTM format, to OMOP.

**Comment by vagarwal77** [comment]
Thanks @FilippSolovev. Looking forward to real code conversion :) 
Currently, i am working on lb domian where trying to transform labtest / lbmethods to NCI codes to LOINC mapping... 

Eager to see a generic approach from this repo...
